### ISSUE TITLE
Can't update partial from Ajax call using these plugin or environment

### ISSUE THREAD

**Issue by leonarpv** [vojtasvoboda/oc-proeventspreview-plugin#1]
Hi, i have some troubles to return/update  data/partial from ajax call api with october.

For example
`
 $(function () {
        $('#calendar').fullCalendar({
            lang: 'es',
            timeFormat: 'HH:mm',
            firstDay: '1',
            dayClick: function (date, jsEvent, view) {
                $.request('onGetDayInventory', {
                    data: {
                        date: date.format(),
                        department_id: $('#department').val(),
                    }
                });
            }
        })
    });
`

and on the controller

`    public function onGetDayInventory()
    {
        $data = input::all();
        $data['restorant_id'] = $this->restorant->id;
        $carbon=new Carbon($data['date']);
        $data['weekday'] =$carbon->englishDayOfWeek;
        $departments = $this->getDepartmentsFacade();
        $schedule = $departments->getSchedulesIntervals($this->restorant,$data);
        return [
            '#modal_department_intervals' => $this->makePartial('modal_department_intervals', [
                'schedules' => $schedule])
        ];
    }
`

But, on the view, nothing change.

I know there are some restrictions with the AJAX API, but I did not think it affected me with this.

Thanks

**Comment by vojtasvoboda** [comment]
Hi, try:

```
$('#calendar').fullCalendar({
  dayClick: function(date, jsEvent, view) {
    alert('Clicked on: ' + date.format());
  }
});
```

If you can see alert popup. Method onGetDayInventory should be in widget (plugins/vojtasvoboda/proeventspreview/widgets/FullCalendar.php), not in controller.
